### ISSUE TITLE
Lock down security group rules

### ISSUE THREAD

**Issue by seansund** [cloud-native-toolkit/terraform-vsi-vpn#11]
|Goal ID|Goal description|Severity|Detail|
|-------|-----------------|--------|------|
|3000404|Check that the inbound rules in a VPC security group do not contain any rules that specify source IP 0.0.0.0/0 to SSH port 22|Critical|VPC security groups allow incoming traffic from 0.0.0.0/0 to port 22 (ssh)|
|3000405|Check that the inbound rules in a VPC security group do not contain any rules that specify source IP 0.0.0.0/0 to RDP ports 3389, 3390|Critical|VPC security groups allow incoming traffic from 0.0.0.0/0 to port 3389 RDP|
|3000410|Check that no VPC security groups have inbound ports open to the internet (0.0.0.0/0)|Critical|Security groups have inbound ports open to internet (0.0.0.0/0)|
|3000411|Check that no VPC security groups have outbound ports open to the internet (0.0.0.0/0)|Critical|Security groups have outbound ports open to internet (0.0.0.0/0)|
|3000406|Check that no rules exist in the default security group of all VPCs|High|The default security group for VPC "r014-aadaba2f-23f4-4204-bf08-107fb01ba960" does not restricts all traffic|
|3000446|Check whether default security group does not allow PING.|Medium|VPC default security group allow PING|

**Comment by Sivasaivm** [comment]
Security Group updated with following rules & a PR request initiated.
Allow Internet egress traffic over port 80&443
Allow all egress traffic to CIDR 10.0.0.0/8
